### ISSUE TITLE
git clone doesn't work

### ISSUE THREAD

**Issue by erikmd** [jcubic/git#11]
Hello,
Thanks for maintaining that nice piece of software!

I've tried to use `git clone` with two different browsers (Firefox and Chromium) on Debian 9, and it didn't work for any of them :-/ (cf. screenshot below)
Can you reproduce this issue, and hopefully find a solution/workaround?
Thanks!

![2019-08-01_00-53-50_Screenshot_git_clone_broken](https://user-images.githubusercontent.com/10367254/62253730-26c13100-b3f7-11e9-9563-f6623383a438.png)

Cc @leunam217 FYI

**Comment by jcubic** [comment]
The project was not updated for a while and isomorphic-git project is still in it's 0.x version and changing behavior, will check that's going on.

**Comment by jcubic** [comment]
The problem was that I've moved hosting for `jcubic.pl` including `proxy.php` file used by git web terminal. it works now.
