### ISSUE TITLE
Website not displaying anything besides the "Fork me on GitHub" banner

### ISSUE THREAD

**Issue by KygekDev** [jcubic/git#14]
Is this an issue with my browser, my network connection or the source code? Thanks.

![image](https://user-images.githubusercontent.com/68368066/145308048-6aba3900-7770-4bcc-9143-44daf5ae0a7e.png)

Browser: Google Chrome version 96.0.4664.45 (64-bit)

**Comment by jcubic** [comment]
Thanks for reporting. I've changed the url to jsdelivr CDN and made mistake, it was so simple change that I didn't tested if the app works.

**Comment by jcubic** [comment]
Should be fixed now.

**Comment by KygekDev** [comment]
Thank you very much.
