### ISSUE TITLE
Move GitHub pages to master

### ISSUE THREAD

**Issue by rampall** [jcubic/git#18]
typoef -> typeof 

https://github.com/jcubic/git/blob/6e41414b4538bdecdc7d74a749d22e41693646d6/js/main.js#L1098

**Comment by jcubic** [comment]
Ok, so you find an error in the git history. What do you expect from this issue?
The error is not present on [gh-pages branch](https://github.com/jcubic/git/blob/gh-pages/js/main.js).

**Comment by rampall** [comment]
I think this is a really fun project. So I cloned the `master` branch locally to play around with it ... and it didn't run because of the little typo in this referenced line. Hence the issue report.

You are right, It is not an issue in the `gh-pages` branch.

**Comment by jcubic** [comment]
Thanks for pointing that out, I need to move GitHub pages to master. I think that when I created this project the only option was a gh-pages branch.

**Comment by jcubic** [comment]
I've changed default branch to gh-pages
