### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by KingsDistributedSystems** [jcubic/git#8]
at line 1038 in main.js you have 'typoef' instead of 'typeof' breaking the script

**Comment by jcubic** [comment]
Thanks for the heads-up, don't you wan to fix this and be in contributors file and in credits command?

You can create a fork and PR and I will merge.

**Comment by jcubic** [comment]
You need to edit gh-pages branch.

**Comment by KingsDistributedSystems** [comment]
The problem does not appear to be in the gh-pages branch. I've edited it in master and I'll make a pull request. I am looking at forking and extending the functionality of the terminal. Is there an interface for plugins? I believe I only need access to the commands and terminal objects. #9

**Comment by KingsDistributedSystems** [comment]
We are building a grid computer for browser/javascript engines. At the moment we are distributing scientific work to compute (think: folding@home). I would be adding commands to interact with the network. https://distributed.computer is our company's website.

I think the plugin API is best like this:
```
terminal.addPlugin = function (callback) { callback(terminal, commands) }
```
Then to add a plugin I would:
```
terminal.addPlugin((terminal, commands) => {
  commands.myCommand = function (cmd) {
    terminal.doSomething()
  }
})
```

**Comment by jcubic** [comment]
Will think about it, I'm not sure if it's good idea to monkey patch jQuery Terminal.

**Comment by jcubic** [comment]
I've exposed global term object which is terminal instance with:
```
term.commands
term.completion
```
You can add commands using first object and completion to second that is handled like this:
```javascript
term.completion[cmd.name].call(
    term,
    string,
    callback,
    files,
    directories
);
```

so if you want to add function `foo` that handle files
```
term.commands['foo'] = function(cmd) {
    if (cmd.args.length == 1) {
        this.echo('Your file is ' + $.terminal.escape_brackets(cmd.args[0]));
    }
};
term.completion['foo'] = function(string, cb, file, dirs) { cb(files); };
```

PS: also fixed the app because it was broken.
